#!/usr/bin/env python3
"""Issue #216 correction-campaign fixture helpers.

Shared builders for the corrected assembler's synthetic evidence trees:
a faithful fresh-mapping artifact (R3 identity probes revalidating
against RETAINED physical probe bytes), closure/authority bindings, and
the #35-faithful transport raw records. Kept in one module so both the
concurrent and assembler test suites derive identical shapes.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "scripts"))

import issue216_receipt as rc
import issue216_physical_authority as _pa

AUTH_DIGEST = _pa.build_authority()["authority_digest"]

# exact physical identity-probe bytes retained on inferswarm02 (kept as
# a committed fixture so the R3 revalidation path is exercised on CPU)
PROBE_BYTES = json.loads(
    (REPO / "tests" / "fixtures_v2d_identity_probe_bytes.json")
    .read_text())


def build_mapping_doc(root: Path, *, attempt: str = "pf1",
                      die_a: tuple[str, str] = ("Vulkan1", "0000:06:00.0"),
                      die_b: tuple[str, str] = ("Vulkan2", "0000:09:00.0"),
                      probe_bytes: dict[str, dict[str, str]] | None = None
                      ) -> dict[str, Any]:
    """Build a fresh-mapping artifact whose identity probes revalidate
    through the ACCEPTED R3 validator against retained raw bytes.

    probe_bytes maps die -> {stdout, stderr}; defaults use the retained
    physical bytes (they contain exactly one `using device` line each at
    the historical BDFs, so overridden die_* pairs must pass matching
    bytes).
    """
    pb = probe_bytes or PROBE_BYTES
    raw_root = root / "preflight" / "mapping" / "raw"
    raw_root.mkdir(parents=True, exist_ok=True)
    import re as _re
    identity_line_re = _re.compile(
        r"using device (?P<selector>Vulkan[0-9]+).*?"
        r"\((?P<bdf>0000:[0-9a-fA-F]{2}:[0-9a-fA-F]{2}\.\d)\)")
    participants = {}
    bindings = []
    for die, (selector, bdf) in (("a", die_a), ("b", die_b)):
        key = selector.lower()
        stdout = pb[key]["stdout"].encode()
        stderr = pb[key]["stderr"].encode()
        (raw_root / f"identity-probe-stdout-{key}.txt").write_bytes(stdout)
        (raw_root / f"identity-probe-stderr-{key}.txt").write_bytes(stderr)
        m = identity_line_re.search(pb[key]["stderr"])
        proof_line = m.group(0) if m else None
        probe = {
            "probe_kind": "NON_CORRECTNESS_BEARING_IDENTITY_PROBE",
            "authorization": "NON_AUTHORIZING",
            "argv": ["/bin/llama-cli", "--device", selector, "-n", "0",
                     "-m", "m.gguf"],
            "exit_code": 0,
            "selector": selector,
            "raw_stdout_path": f"./identity-probe-stdout-{key}.txt",
            "raw_stderr_path": f"./identity-probe-stderr-{key}.txt",
            "stdout_sha256": hashlib.sha256(stdout).hexdigest(),
            "stderr_sha256": hashlib.sha256(stderr).hexdigest(),
            "observed_pci_bdf": bdf.removeprefix("0000:"),
            "identity_proof_line": proof_line,
            "generated_tokens": 0,
            "zero_generation_proof": ["Generation: 0.0 t/s"],
        }
        binding = {
            "selector": selector,
            "device_name": "AMD Radeon Pro V340 (RADV VEGA10)",
            "binding_status": "BOUND",
            "pci_bdf": bdf.removeprefix("0000:"),
            "resolution_mechanism":
                "runtime identity probe (zero generated tokens); the "
                "runtime's own selected-device line states the BDF",
            "identity_probe": probe,
        }
        bindings.append(binding)
        participants[die] = {
            "fresh_selector": selector,
            "fresh_pci_bdf": bdf.removeprefix("0000:"),
            "fresh_device_name": "AMD Radeon Pro V340 (RADV VEGA10)",
            "fresh_binding": binding,
        }
    doc = {
        "schema": "inferswarm.v2d.fresh-mapping/2",
        "campaign_id": rc.CAMPAIGN_ID,
        "attempt_id": attempt,
        "bindings": {"bindings": bindings},
        "participants": participants,
        "fixture": False,
    }
    body = {k: v for k, v in doc.items() if k != "mapping_digest"}
    doc["mapping_digest"] = hashlib.sha256(
        rc.canonical(body)).hexdigest()
    (root / "preflight" / "mapping" / "fresh-mapping.json").write_bytes(
        json.dumps(doc, indent=1, sort_keys=True).encode() + b"\n")
    return doc


def closure_binding() -> dict[str, str]:
    """The current verified closure's binding fields (tests run against
    the live repo tree; the closure is regenerated by the campaign
    tooling commits so this always reflects the pinned producer)."""
    closure = rc.verify_closure(rc.ROOT)
    return {"closure_digest": closure["closure_digest"],
            "producer_head": closure["producer_head"]}


def synth_transport_probe_record(bdf: str, selector_index: int,
                                 match_index: int) -> dict[str, Any]:
    """Faithful #35 raw probe record: identity header + the full frozen
    ladder (both directions x 4 sizes x 8 reps), 200 small transfers,
    8 bidirectional, and load-phase link samples."""
    import random
    rng = random.Random(1234 + selector_index)
    sustained = []
    for direction in ("h2d", "d2h"):
        for size in (4194304, 16777216, 67108864, 134217728):
            base_ms = size / 4194304 * 1.6
            for rep in range(8):
                sustained.append({
                    "bytes": size, "dir": direction, "rep": rep,
                    "ms": round(base_ms * (1 + rng.random() * 0.05), 6)})
    latency = [{"bytes": 4096, "dir": "lat", "rep": i,
                "ms": round(0.09 + rng.random() * 0.2, 6)}
               for i in range(200)]
    bidir = [{"bytes_each_direction": 33554432, "dir": "bidir", "rep": i,
              "ms": round(91.0 + rng.random(), 6)} for i in range(8)]
    header = {"vk_device_index": selector_index,
              "device_name": "AMD Radeon Pro V340 (RADV VEGA10)",
              "name_match_rank": match_index, "api_version": "1.4.305",
              "name_match_count": 2}
    # JSON-ish stream the accepted parser re-parses: header line then
    # the concatenated JSON bodies
    body_json = json.dumps({"sustained": sustained, "latency": latency,
                            "bidir": bidir}, separators=(",", ":"))
    probe_stdout = json.dumps(header, separators=(",", ":")) + "\n" \
        + body_json[1:-1].replace("}{", "}\n{") + "\n"
    link_samples = [{"phase": "idle:pre",
                     "subject": {"current_link_speed": "8.0 GT/s PCIe",
                                 "current_link_width": "16",
                                 "max_link_speed": "8.0 GT/s PCIe",
                                 "max_link_width": "16"},
                     "utc": "2026-09-18T00:00:00Z"}]
    for i in range(12):
        link_samples.append({"phase": f"load:watch{i}",
                             "subject": {
                                 "current_link_speed": "8.0 GT/s PCIe",
                                 "current_link_width": "16",
                                 "max_link_speed": "8.0 GT/s PCIe",
                                 "max_link_width": "16"},
                             "utc": "2026-09-18T00:00:01Z"})
    link_samples.append({"phase": "idle:post",
                         "subject": {"current_link_speed": "8.0 GT/s PCIe",
                                     "current_link_width": "16",
                                     "max_link_speed": "8.0 GT/s PCIe",
                                     "max_link_width": "16"},
                         "utc": "2026-09-18T00:00:02Z"})
    return {
        "schema": "inferswarm.issue35.transport-probe/1",
        "identity": header,
        "probe_stdout": probe_stdout,
        "probe_stderr": "",
        "link_samples": link_samples,
        "twin_binding": {
            "bound": True,
            "identity_probe": {"selector": f"Vulkan{selector_index}",
                               "pci_bdf": bdf.removeprefix("0000:"),
                               "tokens_generated": 0}},
        "subject": {"pci_bdf": bdf.removeprefix("0000:")},
        "measured_utc": "2026-09-18T00:00:00Z",
    }
