#!/usr/bin/env python3
"""Issue #207 R8-G: evidence INPUT manifest + final repository closure
(CPU-only, stdlib).

Correction round 2026-09-17 (maintainer review of PR #208): the single
MANIFEST.sha256 previously covered README.md and terminal-reduction.json
— bytes GENERATED by the reduction itself — so the reducer's manifest
verification failed on its own outputs (digest cycle) and the committed
terminal was R8G_LOCALIZATION_EVIDENCE_BLOCKED. This writer now
produces TWO artifacts with a strict input/closure split:

  evidence/input-manifest.json  (INPUT manifest)
      Covers ONLY immutable reduction inputs: physical capture records,
      raw f32 sidecars, logits-hook JSONLs, seam-anchor row bytes,
      instrumentation records, run driver, per-phase spec records. It
      NEVER lists README.md, terminal-reduction.json, producer-hashes
      .json, CLOSURE.sha256, or itself. The terminal reducer consumes
      and verifies exactly this manifest (file-set equality enforced
      against the evidence/ tree), so no reduction output is ever an
      input to the terminal it constrains.

  CLOSURE.sha256  (FINAL closure; NOT a reducer input)
      Covers the derived/non-input artifacts of the R8-G namespace:
      README.md, terminal-reduction.json, producer-hashes.json, and the
      input manifest itself (the input manifest is an output of this
      writer but an input to the reducer; the closure pins it AFTER the
      reduction has consumed it, which is acyclic: reducer reads inputs
      -> closure covers inputs+outputs). It must not be listed by the
      input manifest and the reducer never reads it.

Deterministic fixed point (required by Issue #207 correction item 4):
  write-inputs -> reduce --write -> write-closure
  then repeat all three; the second pass changes zero bytes.
  Rationale: reduction outputs (terminal-reduction.json) are closure
  rows, not input rows, so regenerating them cannot invalidate the
  input manifest the reducer verifies; and the closure is regenerated
  after every producer/output change, so it always matches on-disk
  bytes. `--check` verifies both artifacts byte-exactly.
"""
import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
from issue207_r8g_authority import R8G_DIR, R8G_PRODUCERS  # noqa: E402

AREA = ROOT / R8G_DIR
EV = AREA / "evidence"
INPUT_MANIFEST = EV / "input-manifest.json"
CLOSURE = AREA / "CLOSURE.sha256"
PRODUCERS = AREA / "producer-hashes.json"

#: artifacts produced by this writer / the reducer — NEVER input rows
DERIVED = {
    "README.md",
    "terminal-reduction.json",
    "producer-hashes.json",
    "CLOSURE.sha256",
    "evidence/input-manifest.json",
}

INPUT_MANIFEST_SCHEMA = "inferswarm.issue207.input-manifest/1"
CLOSURE_SCHEMA_NOTE = ("final repository closure; never an input to the "
                       "terminal reduction it covers")


def sha256_file(path: Path) -> str:
    d = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            d.update(chunk)
    return d.hexdigest()


def input_rows() -> dict:
    rows = {}
    for path in sorted(EV.rglob("*")):
        if path.is_file() and path.name != "input-manifest.json":
            rows[path.relative_to(ROOT).as_posix()] = sha256_file(path)
    return rows


def write_inputs() -> dict:
    rows = input_rows()
    doc = {
        "schema": INPUT_MANIFEST_SCHEMA,
        "campaign": "issue207-r8g-boundary-localization",
        "note": ("immutable reduction inputs only: physical captures, "
                 "raw f32 sidecars, hook JSONLs, anchor rows, "
                 "instrumentation, run driver. Never lists reducer "
                 "outputs or this file."),
        "rows": rows,
    }
    INPUT_MANIFEST.write_text(
        json.dumps(doc, indent=2, sort_keys=True) + "\n")
    return doc


#: the closure covers exactly the derived, non-input artifacts of the
#: R8-G namespace (README, terminal reduction, producer pins, and the
#: input manifest — pinned AFTER the reduction consumed it). It never
#: covers physical evidence (those bytes are pinned by the INPUT
#: manifest) and is never an input to the terminal it contains.
CLOSURE_ROWS = (
    "README.md",
    "terminal-reduction.json",
    "producer-hashes.json",
    "evidence/input-manifest.json",
)


def write_closure() -> dict:
    rows = {}
    for rel in CLOSURE_ROWS:
        rows[rel] = sha256_file(AREA / rel)
    lines = "".join(f"{digest}  {name}\n"
                    for name, digest in sorted(rows.items()))
    CLOSURE.write_text(
        "# " + CLOSURE_SCHEMA_NOTE + "\n" + lines)
    return rows


def check() -> int:
    problems = []
    # input manifest: exact bytes + no derived artifact listed
    try:
        doc = json.loads(INPUT_MANIFEST.read_text())
    except FileNotFoundError:
        print("FAIL: evidence/input-manifest.json missing")
        return 1
    if doc.get("schema") != INPUT_MANIFEST_SCHEMA:
        problems.append("input manifest schema drift")
    rows = doc.get("rows", {})
    for rel, want in rows.items():
        p = ROOT / rel
        if not p.exists():
            problems.append(f"input row missing: {rel}")
        elif sha256_file(p) != want:
            problems.append(f"input digest mismatch: {rel}")
    on_disk = {p.relative_to(ROOT).as_posix()
               for p in EV.rglob("*")
               if p.is_file() and p.name != "input-manifest.json"}
    if set(rows) != on_disk:
        problems.append(
            "input manifest file-set drift: only-listed=%r only-disk=%r"
            % (sorted(set(rows) - on_disk)[:3],
               sorted(on_disk - set(rows))[:3]))
    for bad in DERIVED:
        if (R8G_DIR + "/" + bad) in rows:
            problems.append(f"derived artifact listed as input: {bad}")
    if (ROOT / R8G_DIR / "MANIFEST.sha256").exists():
        problems.append("legacy MANIFEST.sha256 still present")

    # closure: exact bytes
    want_lines = {"README.md", "terminal-reduction.json",
                  "producer-hashes.json", "evidence/input-manifest.json"}
    got_lines = set()
    text = CLOSURE.read_text().splitlines()
    if not text or not text[0].startswith("# "):
        problems.append("closure missing header note")
    for line in text[1:]:
        if not line.strip():
            continue
        digest, name = line.split("  ", 1)
        got_lines.add(name)
        p = AREA / name
        if not p.exists():
            problems.append(f"closure row missing: {name}")
        elif sha256_file(p) != digest:
            problems.append(f"closure digest mismatch: {name}")
    if got_lines != want_lines:
        problems.append("closure row-set drift: %r vs %r"
                        % (sorted(got_lines), sorted(want_lines)))
    if problems:
        for p in problems:
            print("FAIL:", p)
        return 1
    print(json.dumps({"input_rows": len(rows),
                      "closure_rows": len(got_lines), "ok": True}))
    return 0


def write_producers() -> dict:
    pins = {}
    for rel in R8G_PRODUCERS:
        pins[rel] = sha256_file(ROOT / rel)
    PRODUCERS.write_text(json.dumps(pins, indent=2, sort_keys=True) + "\n")
    return pins


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--inputs", action="store_true",
                    help="(re)write evidence/input-manifest.json")
    ap.add_argument("--producers", action="store_true",
                    help="(re)write producer-hashes.json")
    ap.add_argument("--closure", action="store_true",
                    help="(re)write CLOSURE.sha256 from current bytes")
    ap.add_argument("--check", action="store_true",
                    help="verify both artifacts byte-exactly")
    a = ap.parse_args()
    if not (a.inputs or a.closure or a.check or a.producers):
        ap.error("one of --inputs/--producers/--closure/--check required")
    if a.producers:
        pins = write_producers()
        print("wrote", PRODUCERS, len(pins), "rows")
    if a.inputs:
        doc = write_inputs()
        print("wrote", INPUT_MANIFEST, len(doc["rows"]), "rows")
    if a.closure:
        rows = write_closure()
        print("wrote", CLOSURE, len(rows), "rows")
    if a.check:
        return check()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
