#!/usr/bin/env python3
"""Issue #232 — V2-G evidence manifest generator (repo-relative rows).

Rows are repo-root-relative; the manifest never lists itself.
Regenerated by re-running after any evidence edit (never hand-edited).
"""
import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NS = "vulkan-v2-g-pcie-path-remediation"
AREA = ROOT / "docs" / "investigations" / NS


def main() -> int:
    rows = []
    for path in sorted(AREA.rglob("*")):
        if path.is_file() and path.name != "MANIFEST.sha256":
            rel = path.relative_to(ROOT).as_posix()
            rows.append(f"{hashlib.sha256(path.read_bytes()).hexdigest()}  {rel}")
    out = AREA / "MANIFEST.sha256"
    out.write_text("\n".join(rows) + "\n", encoding="utf-8")
    print(f"{len(rows)} rows -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
