"""Parsers over retained RAW Arm-B evidence (pure stdlib, CPU-only, deterministic).

Authority ladder (enforced by the reducer):
  1. raw/low-level observation   -- these parsers read files of this class
  2. derived accounting artifact -- generated by the builder from class-1
  3. stored summary              -- cross-check only, never authority
  4. terminal classification     -- derived, printed, never input
No parser in this package writes to any host or modifies any input file.
"""
