"""Parser/validator for the retained coordinator state-tree inventory
(Issue #117 Arm B) — round-4 exact-file-set enforcement.

Input: evidence/arm-b/observations/coordinator-state-inventory.json — a
machine-readable inventory generated by READ-ONLY filesystem observation
of /srv/inferswarm/state/arm-b/ on inferswarm00 (find/stat/sha256sum;
regeneration script: scripts/issue117_arm_b_observe_hosts.py).

Round-4 semantics (maintainer finding P1-1): prefix-based operational
admission is REPLACED by an exact frozen set of all 14 observed regular
files. The zero-payload derivation is:

  1. observed regular-file set == exact frozen known set (14 files:
     6 data files + 8 operational files — added, removed, or renamed
     files fail closed regardless of name or extension);
  2. every file has its exact expected byte size AND sha256 (a
     digest-changed file fails closed even at an operational path);
  3. every known file has an explicit classification (data vs
     operational) — no file is implicitly "anything under scripts/";
  4. no unexplained file exists.

The eight operational files are additionally retained byte-exact under
evidence/arm-b/raw/coordinator/ and cross-bound below: the retained raw
copy must equal the observed inventory entry (size AND digest), so the
inventory cannot be regenerated around a substituted operational file.

PAYLOAD_EXTENSIONS remains as a diagnostic/reporting aid only; it has
no role in admission or in the zero derivation.
"""
from __future__ import annotations

#: frozen classification of ALL observed regular files under the
#: coordinator Arm-B state tree. "data" = retained campaign metadata
#: (tickets/plan/requirements/deltas/record); "operational" =
#: regenerable driver/tool state (inventory stubs, coordinator-side
#: driver scripts, CPython bytecode caches). Every entry is
#: path -> (classification, bytes, sha256). This table IS the exact
#: known set: admission is set equality, never prefix or extension.
KNOWN_FILES = {
    "authorization/coordinator-deltas.json": (
        "data", 100764,
        "a15e6cee1efb30dd390bf132ba447c14ee7a2edd6a8b22c69645dd6340b9e7cc"),
    "authorization/coordinator-record.json": (
        "data", 303,
        "f28c64f5aa2eef660a5f93183a6d4a16d2f0a80eccd916212f386515f3ec3de7"),
    "authorization/tickets-inferswarm01.json": (
        "data", 23131326,
        "ca53c3560593f75156e6d101900b487210d3e950dc987494bfc92a0cdca9c9f2"),
    "authorization/tickets-inferswarm03.json": (
        "data", 11669777,
        "ab12b934b9483c960a67a0f0b1d5c8a53da5fcca599749917811bad6da3966bb"),
    "source/arm-b-plan.json": (
        "data", 3543,
        "e8416564d63b2f3b114fa70fca8593c88b42a3f662ff7959a91dac20512d3bff"),
    "source/arm-b-requirements.json": (
        "data", 493354,
        "8fe8854a0ba118c9ba598655834d9177b4d1bc9f1ef99a5259834b389e02dde3"),
    "inventory-inferswarm01.json": (
        "operational", 286,
        "48db5b83afaa3c434170d5a88a1c5cf2c81b6826313e02024c76f9df472570aa"),
    "inventory-inferswarm03.json": (
        "operational", 286,
        "3fb8ff2e8dd11d7eb8d099ff57eefebe32d0785f8d0d3ea4fbbc44b799033b19"),
    "scripts/__pycache__/armb_coordinator.cpython-313.pyc": (
        "operational", 9836,
        "8f8cfb8a3a7b867106d69eb54a47a852ed5cd59ad401cb578f13ecbbf39dc2ef"),
    "scripts/__pycache__/armb_plan_core.cpython-313.pyc": (
        "operational", 11912,
        "a397ef1ff49651bb30e704897151ba4d6be5103ed01c7c389e768d25d564f07a"),
    "scripts/armb_common.py": (
        "operational", 4032,
        "2f344c118691d17deb714086260206f71c6f990bd1cbb5def86e5f0dd1297c3c"),
    "scripts/armb_coordinator.py": (
        "operational", 7569,
        "3912974effdf6e8e1472d95a755a866765fc62968027285259d6f50888353a91"),
    "scripts/armb_inventory.py": (
        "operational", 1771,
        "51e9b764540ea81cc1096c32024853614a41beccd7d7eb5a56b7bf48606df373"),
    "scripts/armb_plan_core.py": (
        "operational", 10316,
        "9c8360f4fb308b816e6abd6735bc592bfb67113b623e118c675b4d40cf8271bf"),
}

#: backwards-compatible view of the data-file allowlist (the six
#: retained campaign metadata files)
ALLOWED_DATA_FILES = {
    path: (size, digest)
    for path, (cls, size, digest) in KNOWN_FILES.items()
    if cls == "data"
}

#: the eight operational files (exact paths; retained byte-exact under
#: evidence/arm-b/raw/coordinator/)
OPERATIONAL_FILES = {
    path: (size, digest)
    for path, (cls, size, digest) in KNOWN_FILES.items()
    if cls == "operational"
}

#: frozen totals the exact set must reproduce
EXPECTED_FILE_COUNT = 14
EXPECTED_DATA_BYTES = 35399067
EXPECTED_OPERATIONAL_BYTES = 46008
EXPECTED_TOTAL_BYTES = 35445075

#: file extensions that indicate model payload objects; DIAGNOSTIC AND
#: REPORTING AID ONLY — admission and the zero-payload derivation use
#: exact set membership, never extensions.
PAYLOAD_EXTENSIONS = (".safetensors", ".bin", ".gguf", ".pt", ".pth", ".ckpt")


def derive(inventory: dict) -> dict:
    """Derive storage accounting from an observed inventory."""
    entries = inventory.get("entries", [])
    digests = inventory.get("regular_file_digests", {})
    problems = []
    files = {}
    for e in entries:
        rel, ftype = e.get("path"), e.get("type")
        if ftype == "d":
            continue
        if ftype == "l":
            problems.append(f"symlink present in coordinator tree: {rel}")
            continue
        if ftype != "f":
            problems.append(f"non-regular non-dir entry: {rel} ({ftype})")
            continue
        files[rel] = e.get("size")
    # every regular file must carry a digest
    for rel in files:
        if rel not in digests:
            problems.append(f"regular file lacks sha256 in inventory: {rel}")
    # the inventory's own declared aggregates must match its entries
    declared_count = inventory.get("total_file_count")
    if isinstance(declared_count, int) and declared_count != len(files):
        problems.append(
            f"inventory total_file_count {declared_count} != entry count "
            f"{len(files)}")
    declared_total = inventory.get("total_bytes")
    entry_total = sum(files.values())
    if isinstance(declared_total, int) and declared_total != entry_total:
        problems.append(
            f"inventory total_bytes {declared_total} != per-file sum "
            f"{entry_total}")
    declared_links = inventory.get("symlink_count")
    link_count = sum(1 for e in entries if e.get("type") == "l")
    if isinstance(declared_links, int) and declared_links != link_count:
        problems.append(
            f"inventory symlink_count {declared_links} != observed "
            f"{link_count}")
    # exact-set admission (P1-1): the observed regular-file set must
    # EQUAL the frozen known set. Any added, removed, or renamed file
    # fails closed here — including scripts/payload.py, scripts/payload,
    # scripts/random.json, or any unknown file with a known payload
    # extension.
    observed_set = set(files)
    known_set = set(KNOWN_FILES)
    unexpected = sorted(observed_set - known_set)
    missing = sorted(known_set - observed_set)
    if unexpected:
        problems.append(f"unexpected coordinator-held files: {unexpected}")
    if missing:
        problems.append(f"known coordinator files missing: {missing}")
    # exact identity for EVERY known file: size AND sha256, data and
    # operational alike (a digest-changed file at a known operational
    # path fails closed)
    for rel, (cls, size, digest) in KNOWN_FILES.items():
        if files.get(rel) is None:
            continue  # already reported as missing
        if files[rel] != size:
            problems.append(
                f"coordinator {cls} file size drift: {rel} "
                f"({files[rel]} != {size})")
        elif digests.get(rel) != digest:
            problems.append(f"coordinator {cls} file digest drift: {rel}")
    # frozen totals the exact set must reproduce
    data_total = sum(files.get(rel, 0) for rel in ALLOWED_DATA_FILES)
    operational_total = sum(
        files.get(rel, 0) for rel in OPERATIONAL_FILES)
    if not problems:
        if len(files) != EXPECTED_FILE_COUNT:
            problems.append(
                f"exact-set count {len(files)} != frozen {EXPECTED_FILE_COUNT}")
        if data_total != EXPECTED_DATA_BYTES:
            problems.append(
                f"data-file total {data_total} != frozen "
                f"{EXPECTED_DATA_BYTES}")
        if operational_total != EXPECTED_OPERATIONAL_BYTES:
            problems.append(
                f"operational-file total {operational_total} != frozen "
                f"{EXPECTED_OPERATIONAL_BYTES}")
        if entry_total != EXPECTED_TOTAL_BYTES:
            problems.append(
                f"tree total {entry_total} != frozen {EXPECTED_TOTAL_BYTES}")
    # payload detection: DIAGNOSTIC ONLY. Under exact-set admission any
    # payload-named file is already 'unexpected'; this listing exists
    # for the report, not for the zero derivation.
    payload_files = sorted(
        rel for rel in files
        if rel.lower().endswith(PAYLOAD_EXTENSIONS))
    return {
        "problems": problems,
        "observed_file_count": len(files),
        "observed_total_bytes": sum(files.values()),
        "data_file_total_bytes": data_total,
        "operational_file_total_bytes": operational_total,
        "model_payload_files": payload_files,
        "model_payload_bytes_under_state_arm_b": sum(
            files.get(rel, 0) for rel in payload_files),
    }


def verify_raw_retention(raw_coordinator_dir) -> list:
    """Cross-bind the retained raw copies (evidence/arm-b/raw/
    coordinator/) to the frozen operational-file pins. Returns a list
    of problems (empty == every retained copy is byte-exact)."""
    import hashlib
    problems = []
    for rel, (size, digest) in OPERATIONAL_FILES.items():
        path = f"{raw_coordinator_dir}/{rel}"
        try:
            data = open(path, "rb").read()
        except OSError as exc:
            problems.append(f"retained coordinator copy missing: {rel} "
                            f"({exc})")
            continue
        if len(data) != size:
            problems.append(
                f"retained coordinator copy size drift: {rel} "
                f"({len(data)} != {size})")
        elif hashlib.sha256(data).hexdigest() != digest:
            problems.append(
                f"retained coordinator copy digest drift: {rel}")
    return problems
