"""Parser/validator for the retained coordinator state-tree inventory
(Issue #117 Arm B).

Input: evidence/arm-b/observations/coordinator-state-inventory.json — a
machine-readable inventory generated by READ-ONLY filesystem observation
of /srv/inferswarm/state/arm-b/ on inferswarm00 (find/stat/sha256sum;
regeneration script: scripts/issue117_arm_b_observe_hosts.py). This module
derives the storage accounting from the inventory entries; nothing is
hard-coded except the FROZEN allowlist of coordinator-held data files,
which is a retention decision, not an observation.
"""
from __future__ import annotations

#: frozen allowlist of data files the coordinator MAY retain under its
#: Arm-B state tree (name -> (bytes, sha256)). Everything else in the tree
#: must be one of the ALLOWED_OPERATIONAL entr(ies) below (regenerable
#: driver/tool state, no model payload). Any other entry — whatever its
#: name or extension — fails closed.
ALLOWED_DATA_FILES = {
    "authorization/coordinator-deltas.json": (
        100764, "a15e6cee1efb30dd390bf132ba447c14ee7a2edd6a8b22c69645dd6340b9e7cc"),
    "authorization/coordinator-record.json": (
        303, "f28c64f5aa2eef660a5f93183a6d4a16d2f0a80eccd916212f386515f3ec3de7"),
    "authorization/tickets-inferswarm01.json": (
        23131326, "ca53c3560593f75156e6d101900b487210d3e950dc987494bfc92a0cdca9c9f2"),
    "authorization/tickets-inferswarm03.json": (
        11669777, "ab12b934b9483c960a67a0f0b1d5c8a53da5fcca599749917811bad6da3966bb"),
    "source/arm-b-plan.json": (
        3543, "e8416564d63b2f3b114fa70fca8593c88b42a3f662ff7959a91dac20512d3bff"),
    "source/arm-b-requirements.json": (
        493354, "8fe8854a0ba118c9ba598655834d9177b4d1bc9f1ef99a5259834b389e02dde3"),
}

#: operational (regenerable) entries allowed in the tree: participant
#: inventory stubs and the coordinator-side driver scripts + their CPython
#: bytecode caches. These carry no model payload; their digests are NOT
#: pinned (they are not evidence), but their presence must be exactly this
#: set of paths and they must be regular files.
ALLOWED_OPERATIONAL_PREFIXES = (
    "inventory-inferswarm01.json",
    "inventory-inferswarm03.json",
    "scripts/",
)

#: file extensions that indicate model payload objects; used only as a
#: REPORTING aid — allowlisting is by exact path set, never by extension.
PAYLOAD_EXTENSIONS = (".safetensors", ".bin", ".gguf", ".pt", ".pth", ".ckpt")


def derive(inventory: dict) -> dict:
    """Derive storage accounting from an observed inventory."""
    entries = inventory.get("entries", [])
    digests = inventory.get("regular_file_digests", {})
    problems = []
    files = {}
    for e in entries:
        rel, ftype = e.get("path"), e.get("type")
        if ftype == "d":
            continue
        if ftype == "l":
            problems.append(f"symlink present in coordinator tree: {rel}")
            continue
        if ftype != "f":
            problems.append(f"non-regular non-dir entry: {rel} ({ftype})")
            continue
        files[rel] = e.get("size")
    # every regular file must carry a digest
    for rel in files:
        if rel not in digests:
            problems.append(f"regular file lacks sha256 in inventory: {rel}")
    # the inventory's own declared aggregates must match its entries
    declared_count = inventory.get("total_file_count")
    if isinstance(declared_count, int) and declared_count != len(files):
        problems.append(
            f"inventory total_file_count {declared_count} != entry count "
            f"{len(files)}")
    declared_total = inventory.get("total_bytes")
    entry_total = sum(files.values())
    if isinstance(declared_total, int) and declared_total != entry_total:
        problems.append(
            f"inventory total_bytes {declared_total} != per-file sum "
            f"{entry_total}")
    declared_links = inventory.get("symlink_count")
    link_count = sum(1 for e in entries if e.get("type") == "l")
    if isinstance(declared_links, int) and declared_links != link_count:
        problems.append(
            f"inventory symlink_count {declared_links} != observed "
            f"{link_count}")
    # allowlist enforcement: data files exact; everything else operational
    unexpected = sorted(
        rel for rel in files
        if rel not in ALLOWED_DATA_FILES
        and not any(rel == p or rel.startswith(p)
                    for p in ALLOWED_OPERATIONAL_PREFIXES))
    missing = sorted(rel for rel in ALLOWED_DATA_FILES if rel not in files)
    if unexpected:
        problems.append(f"unexpected coordinator-held files: {unexpected}")
    if missing:
        problems.append(f"allowlisted data files missing: {missing}")
    # digest enforcement for the data files
    for rel, (size, digest) in ALLOWED_DATA_FILES.items():
        if files.get(rel) != size:
            problems.append(
                f"coordinator data file size drift: {rel} "
                f"({files.get(rel)} != {size})")
        elif digests.get(rel) != digest:
            problems.append(f"coordinator data file digest drift: {rel}")
    # payload detection is independent of names: ANY file with a payload
    # extension anywhere in the tree is coordinator-held model payload
    payload_files = sorted(
        rel for rel in files
        if rel.lower().endswith(PAYLOAD_EXTENSIONS))
    data_total = sum(files.get(rel, 0) for rel in ALLOWED_DATA_FILES)
    operational_total = sum(
        size for rel, size in files.items() if rel not in ALLOWED_DATA_FILES)
    return {
        "problems": problems,
        "observed_file_count": len(files),
        "observed_total_bytes": sum(files.values()),
        "data_file_total_bytes": data_total,
        "operational_file_total_bytes": operational_total,
        "model_payload_files": payload_files,
        "model_payload_bytes_under_state_arm_b": sum(
            files.get(rel, 0) for rel in payload_files),
    }
